[package]
name = "d3bug64"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.5"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
yew = { version = "0.21.0", features = ["csr"] }
weblog = "0.3.0"
wasm-bindgen = "0.2.92"
yew-router = "0.18.0"
